'''

topic : Hyposhesis Testing

defination : Hypothesis testing is a statistical method used to make decisions about a population based on a sample of data. It involves formulating a null hypothesis (H0) and an alternative hypothesis (H1), and then using statistical tests to determine whether there is enough evidence to reject the null hypothesis in favor of the alternative hypothesis.    
            - The null hypothesis typically represents a default position or a statement of no effect, while the alternative hypothesis represents a claim that we want to test against the null hypothesis.    
            - The process of hypothesis testing involves collecting data, calculating a test statistic, and comparing it to a critical value or using a p-value to determine the statistical significance of the results.   


ex : 1. A pharmaceutical company wants to test the effectiveness of a new drug. The null hypothesis (H0) is that the drug has no effect on patients, while the alternative hypothesis (H1) is that the drug has a positive effect. The company conducts a clinical trial and collects data on patient outcomes. They then perform a hypothesis test to determine if there is enough evidence to reject the null hypothesis and conclude that the drug is effective.  
     2. A marketing team wants to test whether a new advertising campaign has increased sales. The null hypothesis (H0) is that the campaign has no effect on sales, while the alternative hypothesis (H1) is that the campaign has increased sales. The team collects sales data before and after the campaign and performs a hypothesis test to determine if there is a statistically significant increase in sales.
     3. A researcher wants to test whether a new teaching method improves student performance. The null hypothesis (H0) is that the teaching method has no effect on student performance, while the alternative hypothesis (H1) is that the teaching method improves student performance. The researcher collects data on student test scores before and after implementing the new teaching method and performs a hypothesis test to determine if there is a significant improvement in scores.
     4. A company wants to test whether a new manufacturing process reduces defects. The null hypothesis (H0) is that the new process has no effect on defect rates, while the alternative hypothesis (H1) is that the new process reduces defects. The company collects data on defect rates before and after implementing the new process and performs a hypothesis test to determine if there is a significant reduction in defects.
     5. A political analyst wants to test whether a new policy has increased public approval ratings. The null hypothesis (H0) is that the policy has no effect on approval ratings, while the alternative hypothesis (H1) is that the policy has increased approval ratings. The analyst collects data on approval ratings before and after the policy implementation and performs a hypothesis test to determine if there is a significant increase in approval ratings. 

real life scenario : 1. A company wants to test whether a new employee training program has improved productivity. The null hypothesis (H0) is that the training program has no effect on productivity, while the alternative hypothesis (H1) is that the training program has improved productivity. The company collects data on employee performance before and after the training program and performs a hypothesis test to determine if there is a significant improvement in productivity.  
                   2. A school wants to test whether a new curriculum has improved student performance. The null hypothesis (H0) is that the new curriculum has no effect on student performance, while the alternative hypothesis (H1) is that the new curriculum has improved student performance. The school collects data on student test scores before and after implementing the new curriculum and performs a hypothesis test to determine if there is a significant improvement in scores.
                   3. A restaurant wants to test whether a new menu item has increased sales. The null hypothesis (H0) is that the new menu item has no effect on sales, while the alternative hypothesis (H1) is that the new menu item has increased sales. The restaurant collects data on sales before and after introducing the new menu item and performs a hypothesis test to determine if there is a significant increase in sales.
                   4. A city government wants to test whether a new traffic policy has reduced congestion. The null hypothesis (H0) is that the new traffic policy has no effect on congestion, while the alternative hypothesis (H1) is that the new traffic policy has reduced congestion. The city collects data on traffic congestion before and after implementing the new policy and performs a hypothesis test to determine if there is a significant reduction in congestion.
                   5. A sports team wants to test whether a new training regimen has improved player performance. The null hypothesis (H0) is that the new training regimen has no effect on player performance, while the alternative hypothesis (H1) is that the new training regimen has improved player performance. The team collects data on player performance metrics before and after implementing the new training regimen and performs a hypothesis test to determine if there is a significant improvement in performance. 

case study : 1. A company wants to test whether a new marketing strategy has increased sales. The null hypothesis (H0) is that the new marketing strategy has no effect on sales, while the alternative hypothesis (H1) is that the new marketing strategy has increased sales. The company collects data on sales before and after implementing the new marketing strategy and performs a hypothesis test to determine if there is a significant increase in sales. The results of the hypothesis test show that there is a statistically significant increase in sales, leading the company to reject the null hypothesis and conclude that the new marketing strategy is effective.  
            2. A researcher wants to test whether a new drug is effective in treating a certain medical condition. The null hypothesis (H0) is that the drug has no effect on patients, while the alternative hypothesis (H1) is that the drug has a positive effect. The researcher conducts a clinical trial and collects data on patient outcomes. After performing a hypothesis test, the results show that there is a statistically significant improvement in patient outcomes, leading the researcher to reject the null hypothesis and conclude that the drug is effective.  
            3. A school wants to test whether a new teaching method has improved student performance. The null hypothesis (H0) is that the teaching method has no effect on student performance, while the alternative hypothesis (H1) is that the teaching method improves student performance. The school collects data on student test scores before and after implementing the new teaching method and performs a hypothesis test. The results show that there is a statistically significant improvement in test scores, leading the school to reject the null hypothesis and conclude that the new teaching method is effective.  
            4. A company wants to test whether a new manufacturing process reduces defects. The null hypothesis (H0) is that the new process has no effect on defect rates, while the alternative hypothesis (H1) is that the new process reduces defects. The company collects data on defect rates before and after implementing the new process and performs a hypothesis test. The results show that there is a statistically significant reduction in defects, leading the company to reject the null hypothesis and conclude that the new manufacturing process is effective. 

use in ai ml : 1. In machine learning, hypothesis testing can be used to evaluate the performance of a model. For example, a data scientist may want to test whether a new algorithm performs better than an existing one. The null hypothesis (H0) could be that there is no difference in performance between the two algorithms, while the alternative hypothesis (H1) could be that the new algorithm performs better. The data scientist would then collect performance metrics from both algorithms and perform a hypothesis test to determine if there is a statistically significant difference in performance.  
                 2. In natural language processing (NLP), hypothesis testing can be used to evaluate the effectiveness of a new language model. For instance, a researcher may want to test whether a new language model generates more coherent sentences than an existing model. The null hypothesis (H0) could be that there is no difference in coherence between the two models, while the alternative hypothesis (H1) could be that the new model generates more coherent sentences. The researcher would then collect samples of generated sentences from both models and perform a hypothesis test to determine if there is a statistically significant difference in coherence.  
                 3. In computer vision, hypothesis testing can be used to evaluate the performance of a new image recognition algorithm. For example, a researcher may want to test whether a new algorithm has a higher accuracy rate than an existing one. The null hypothesis (H0) could be that there is no difference in accuracy between the two algorithms, while the alternative hypothesis (H1) could be that the new algorithm has a higher accuracy rate. The researcher would then collect accuracy metrics from both algorithms and perform a hypothesis test to determine if there is a statistically significant difference in accuracy. 
                 4. In reinforcement learning, hypothesis testing can be used to evaluate the effectiveness of a new policy. For instance, a researcher may want to test whether a new policy leads to higher rewards than an existing policy. The null hypothesis (H0) could be that there is no difference in rewards between the two policies, while the alternative hypothesis (H1) could be that the new policy leads to higher rewards. The researcher would then collect reward data from both policies and perform a hypothesis test to determine if there is a statistically significant difference in rewards.
                 5. In anomaly detection, hypothesis testing can be used to determine whether a detected anomaly is statistically significant. For example, a data scientist may want to test whether a sudden spike in network traffic is an anomaly or just random variation. The null hypothesis (H0) could be that the spike is due to random variation, while the alternative hypothesis (H1) could be that the spike is an anomaly. The data scientist would then collect data on network traffic and perform a hypothesis test to determine if there is a statistically significant spike in traffic, indicating an anomaly. 

def def solution using code :
    import numpy as np
    from scipy import stats

    # Sample data: sales before and after implementing a new marketing strategy
    sales_before = [100, 110, 120, 130, 140]
    sales_after = [150, 160, 170, 180, 190]

    # Perform a paired t-test
    t_statistic, p_value = stats.ttest_rel(sales_after, sales_before)

    print("T-statistic:", t_statistic)
    print("P-value:", p_value)

conclusion :
        Hypothesis testing is a fundamental statistical method that allows researchers and analysts to make informed decisions based on data. By formulating null and alternative hypotheses, collecting data, and performing statistical tests, we can determine whether there is enough evidence to reject the null hypothesis in favor of the alternative hypothesis. This process is widely used in various fields, including medicine, marketing, education, and artificial intelligence, to evaluate the effectiveness of new treatments, strategies, methods, and algorithms. Understanding hypothesis testing is essential for making data-driven decisions and advancing knowledge in many domains.
            






'''